### PR TITLE
Issue #10 - Router and Route interface.

### PR DESCRIPTION
**Pull request by dkraczkowski**

### CODE REVIEW

**Comment by smalot** [comment]
I have one remark on your code.
When creating interface, I usually add `Interface` as a suffix.

This avoids any mistake when using "Route" object which can be an interface or a class, depending only the namespace.

A great documentation: https://www.php-fig.org/bylaws/psr-naming-conventions/

**Comment by dkraczkowski** [comment]
@smalot  I have used to do this but to be honest couple years ago I have changed my mind if comes to suffixes around traits and interfaces from the following reasons:
- It looks terrible (I know, this is very subjective one)
- Brings no value (all IDEs are capable of informing you whether the identifier is a class name, trait or interface)
- Makes interfaces' name longer
- There were (still are) a lot of complains from community that this is a mistake
- This convention destroys community, people tend to think if they suffix class with `Interface` they code against contract and follow good practices.
- The standard is not consistent- I mean why do we not prefix classes with `Class` and functions with `Function` prefixes?

I am happy to discuss this further ;)

**Comment by dkraczkowski** [comment]
Just to be clear, I do understand why standards are there for and why I should use them. 
I am always trying to follow standards I like consistency, I like rules (they make life easier and world maintainable). If I would create a psr package I would for sure go for all the rules that are recommended by PSR group. On the other hand being a creator is also being a critic- as developers we should criticise the world around us to make it better a place. I hope this short explanation makes sense to you :)

**Comment by smalot** [comment]
Sounds good for me, no problem  ;)
In all cases, your code is very smart !

I love your integration of:
- middlewares
- modules
- listener

Keep going !

**Comment by dkraczkowski** [comment]
Thanks :)

**Pull request merged**
